/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UserRegistration_JUnitTest;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Lib classUnderTest = new Lib();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
